services:
  mysql:
    image: mysql:8.0
    container_name: financas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financas
      MYSQL_USER: financas_user
      MYSQL_PASSWORD: financas_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
